/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResearchIndexRouteImport } from './routes/research/index'
import { Route as ResearchIdRouteImport } from './routes/research/$id'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PropertiesIdRouteImport } from './routes/properties/$id'
import { Route as AdminLoginRouteImport } from './routes/admin/login'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIndexRoute = ResearchIndexRouteImport.update({
  id: '/research/',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIdRoute = ResearchIdRouteImport.update({
  id: '/research/$id',
  path: '/research/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/research': typeof ResearchIndexRoute
  '/research/$id': typeof ResearchIdRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/research': typeof ResearchIndexRoute
  '/research/$id': typeof ResearchIdRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/research/': typeof ResearchIndexRoute
  '/research/$id': typeof ResearchIdRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/admin/login' | '/research' | '/research/$id' | '/properties/$id' | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/login' | '/research' | '/research/$id' | '/properties/$id' | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/login'
    | '/research/'
    | '/research/$id'
    | '/properties/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ResearchIndexRoute: typeof ResearchIndexRoute
  ResearchIdRoute: typeof ResearchIdRoute
  PropertiesIdRoute: typeof PropertiesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/': {
      id: '/research/'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/$id': {
      id: '/research/$id'
      path: '/research/$id'
      fullPath: '/research/$id'
      preLoaderRoute: typeof ResearchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ResearchIndexRoute: ResearchIndexRoute,
  ResearchIdRoute: ResearchIdRoute,
  PropertiesIdRoute: PropertiesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
declare module '@tanstack/react-router' {
  interface Register {
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
