// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  const SUPABASE_URL = "https://lxzzvlcvkphsvdsiuadj.supabase.co";
  const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4enp2bGN2a3Boc3Zkc2l1YWRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY0MjUwNzcsImV4cCI6MjA5MjAwMTA3N30.Mz55OVDHo8hJk2bsJWi5e-HMftfH2Yl_3ErZpt4N3OI";

  console.log("Supabase Client Init (HARDCODED): Connecting to", SUPABASE_URL);

  console.log("Supabase Client Init: Connecting to", SUPABASE_URL);

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

